modified hardinfo to upstream version instead of latest release, modified libwebkit, still failing

diff --git a/libwebkit/receipt b/libwebkit/receipt
--- a/libwebkit/receipt
+++ b/libwebkit/receipt
@@ -12,7 +12,7 @@ WEB_SITE="https://webkitgtk.org"
 WGET_URL="$WEB_SITE/releases/$TARBALL"
 HOST_ARCH="x86_64 i486 arm"
 
-DEPENDS="gtk+3 enchant libxslt expat gtk+ jpeg libpng libxml2 sqlite \
+DEPENDS="gtk+3 enchant libxslt expat jpeg libpng libxml2 sqlite \
 xorg-libICE xorg-libSM xorg-libX11 xorg-libXau xorg-libXcomposite \
 xorg-libXcursor xorg-libXdmcp xorg-libXext xorg-libXfixes xorg-libXinerama \
 xorg-libXrandr xorg-libXrender xorg-libXt acl xorg-libXdamage libsoup \
@@ -24,52 +24,54 @@ libtasn1-dev glib-networking-dev ruby harfbuzz-dev"
 
 # Handle cross compilation.
 case "$ARCH" in
-	i?86) 
-		BUILD_DEPENDS="$BUILD_DEPENDS gtk-dev tar gettext m4 bison flex gperf
-		autoconf automake gtk-doc libtool" ;;
-	x86_64) 
-		BUILD_DEPENDS="$BUILD_DEPENDS tar gettext m4 bison flex gperf
-		autoconf automake gtk-doc libtool gtk+3-dev libepoxy-dev
-		mesa-dev xorg-libXtst-dev xorg-libXxf86vm-dev rubygems
-		glib-dev" ;;
+        i?86) 
+                BUILD_DEPENDS="$BUILD_DEPENDS gtk-dev tar gettext m4 bison flex gperf
+                autoconf automake gtk-doc libtool" ;;
+        x86_64) 
+                BUILD_DEPENDS="$BUILD_DEPENDS tar gettext m4 bison flex gperf
+                autoconf automake libtool gtk+3-dev libepoxy-dev
+                mesa-dev xorg-libXtst-dev xorg-libXxf86vm-dev rubygems
+                glib-dev libiconv-dev" ;;
 esac
 
 # Rules to configure and make the package.
 compile_rules()
 {
-	# libwebkit does not like parallel builds.
-	#~ export MAKEFLAGS=$(echo $MAKEFLAGS | sed 's/-j[0-9]*/-j1/')
-	export CXXFLAGS="$CXXFLAGS -I/usr/include/harfbuzz/ -Wno-expansion-to-defined"
-	# fix Bug 84526: webkit-gtk-1.8.0 fails to build with --disable-video
-	# Build fix with newer bison 2.6
-	#~ if [ ! "$continue" ]; then
-		#~ for file_diff in $stuff/*.diff; do
-			#~ echo -n "Applying patch $(basename $file_diff)"
-			#~ patch -Np1 -i $file_diff > /dev/null
-			#~ status
-		#~ done
-		#~ patch -p0 < $stuff/CodeGeneratorGObject-bug-84526.patch || exit 1
-	#~ fi
-	# Build
-	./configure \
-		--enable-introspection=no \
-		--enable-video=no \
-		--enable-jit=yes \
-		--disable-webgl \
-		--disable-geolocation \
-		--with-unicode-backend=glib \
-		--with-gtk=3.0 \
-		--disable-gtk-doc \
-		$CONFIGURE_ARGS &&
-	make all stamp-po 2>&1 | grep -v Source/WebCore/dom/testing &&
-	make install 2>&1 | \
-		grep -Ev '(/usr/share/gtk-doc/html|Documentation/webkitgtk/version.xml)' &&
-	cp -a $src/Programs/GtkLauncher $DESTDIR/usr/bin
+        # libwebkit does not like parallel builds.
+        #~ export MAKEFLAGS=$(echo $MAKEFLAGS | sed 's/-j[0-9]*/-j1/')
+        export CXXFLAGS="$CXXFLAGS -I/usr/include/harfbuzz/ -Wno-expansion-to-defined -Wno-unused-local-typedefs"
+        export LDFLAGS="$LDFLAGS -liconv"
+        # fix BugÂ 84526: webkit-gtk-1.8.0 fails to build with --disable-video
+        # Build fix with newer bison 2.6
+        #~ if [ ! "$continue" ]; then
+                #~ for file_diff in $stuff/*.diff; do
+                        #~ echo -n "Applying patch $(basename $file_diff)"
+                        #~ patch -Np1 -i $file_diff > /dev/null
+                        #~ status
+                #~ done
+                #~ patch -p0 < $stuff/CodeGeneratorGObject-bug-84526.patch || exit 1
+        #~ fi
+            # Build
+        ./configure \
+                --enable-introspection=no \
+                --enable-video=no \
+                --enable-jit=yes \
+                --disable-webgl \
+                --disable-geolocation \
+                --with-unicode-backend=glib \
+                --disable-webkit2 \
+                --with-gtk=3.0 \
+                --disable-gtk-doc \
+                $CONFIGURE_ARGS &&
+        make all stamp-po 2>&1 | grep -v Source/WebCore/dom/testing &&
+        make install 2>&1 | \
+                grep -Ev '(/usr/share/gtk-doc/html|Documentation/webkitgtk/version.xml)' &&
+        cp -a $src/Programs/GtkLauncher $DESTDIR/usr/bin
 }
 
 # Rules to gen a SliTaz package suitable for Tazpkg.
 genpkg_rules()
 {
-	mkdir -p $fs/usr/lib
-	cp -a $install/usr/lib/*.so* $fs/usr/lib
-}
+        mkdir -p $fs/usr/lib
+        cp -a $install/usr/lib/*.so* $fs/usr/lib
+}    
